---
- name: krb5 설치
  yum:
    name: ['krb5-server', 'krb5-libs', 'krb5-workstation']
    state: latest

- name: kdc 설정 복사
  template:
    src: kdc.conf.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: krb5 설정 복사
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: 도메인이름 변경
  replace:
    path: /var/kerberos/krb5kdc/kadm5.acl
    regexp: 'EXAMPLE.COM'
    replace: "{{ krb_realm }}"

- name: principal 존재 확인
  stat:
    path: /var/kerberos/krb5kdc/principal
  register: stat_result

- name: KDC 데이터베이스 생성
  shell: kdb5_util create -r {{ krb_realm }} -P {{ kadmin_pass }} -s
  when: not stat_result.stat.exists

- name: root 계정 생성
  shell: |
    kadmin.local -q "addprinc -pw {{ kadmin_pass }} root/admin"
    kadmin.local -q "add_principal -randkey kafka01.foo.bar@FOO.BAR"
    kadmin.local -q "add_principal -randkey kafka02.foo.bar@FOO.BAR"
    kadmin.local -q "add_principal -randkey kafka03.foo.bar@FOO.BAR"
    kadmin.local -q "add_principal -randkey zk01.foo.bar@FOO.BAR"
    kadmin.local -q "add_principal -randkey zk02.foo.bar@FOO.BAR"
    kadmin.local -q "add_principal -randkey zk03.foo.bar@FOO.BAR"

- name: 서비스 실행 확인
  systemd:
    state: started
    name: "{{ item }}"
    enabled: yes
  with_items:
    - krb5kdc
    - kadmin