---
- hosts: kafkahosts
  become: true
  connection: ssh
  vars:
    - zookeeperinfo: zk01.foo.bar:2181,zk02.foo.bar:2181,zk03.foo.bar:2181/kafka1
    - dir_path: /data/kafka1-logs
  roles:
    - common
    - kafka